a, b=map(int, input().split())
c=[]
c.append(a+b)
c.append(b+a)
c.append(a-b)
c.append(b-a)
c.append(a*b)
c.append(b*a)
c.append(a/b)
c.append(b/a)
c.append(a**b)
c.append(b**a)
value=max(c)
print(f"{value:.6f}") 
